services:
  - type: web
    name: social-marketplace
    env: node
    buildCommand: |
      npm ci --include=de
      npx tailwindcss -i ./public/css/tailwind.css -o ./public/css/output.css --minify
      npm run generate:css
      npm run build:ts:client
      npm run build:ts:server
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.11.0