import nodemailer from 'nodemailer';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

// Debug: Check if env variables are loaded
console.log('📧 Email Service Configuration:');
console.log('SMTP_HOST:', process.env.SMTP_HOST);
console.log('SMTP_PORT:', process.env.SMTP_PORT);
console.log('SMTP_USER:', process.env.SMTP_USER ? '✅ Set' : '❌ Not set');
console.log('SMTP_PASS:', process.env.SMTP_PASS ? '✅ Set' : '❌ Not set');
console.log('EMAIL_FROM:', process.env.EMAIL_FROM);

const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.gmail.com',
  port: parseInt(process.env.SMTP_PORT || '587'),
  secure: false, // true for 465, false for other ports
  auth: {
    user: process.env.SMTP_USER || '',
    pass: process.env.SMTP_PASS || '',
  },
});

export interface WelcomeEmailData {
  email: string;
  username: string;
  password: string;
}

export const sendWelcomeEmail = async (data: WelcomeEmailData) => {
  const html = `
    <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #e0e0e0; border-radius: 10px; overflow: hidden;">
      <div style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); padding: 30px; text-align: center;">
        <h1 style="color: white; margin: 0; font-size: 28px;">🎉 Welcome to Collectible Trading Post!</h1>
      </div>
      
      <div style="padding: 30px;">
        <p style="font-size: 16px; color: #333;">Hello <strong style="color: #667eea;">${data.username}</strong>,</p>
        <p style="font-size: 16px; color: #333;">Your account has been successfully created. Here are your login credentials:</p>
        
        <div style="background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 25px 0; border-left: 4px solid #667eea;">
          <p style="margin: 10px 0; font-size: 14px;"><strong style="color: #495057;">📧 Email:</strong> <span style="color: #667eea;">${data.email}</span></p>
          <p style="margin: 10px 0; font-size: 14px;"><strong style="color: #495057;">👤 Username:</strong> <span style="color: #667eea;">${data.username}</span></p>
          <p style="margin: 10px 0; font-size: 14px;"><strong style="color: #495057;">🔑 Password:</strong> <code style="background: #fff; padding: 4px 8px; border-radius: 4px; font-size: 16px; font-weight: bold; color: #dc3545;">${data.password}</code></p>
        </div>
        
        <div style="background: #fff3cd; border: 1px solid #ffc107; padding: 15px; border-radius: 8px; margin: 20px 0;">
          <p style="margin: 0; color: #856404; font-size: 14px;">
            ⚠️ <strong>Important Security Notice:</strong> This password was generated by the system. 
            Please <strong style="color: #dc3545;">change your password immediately</strong> after your first login.
          </p>
        </div>
        
        <p style="font-size: 15px; color: #333;">You can start exploring and trading collectibles right away!</p>
        
        <div style="text-align: center; margin: 30px 0;">
          <a href="${process.env.APP_URL || 'http://localhost:3000'}" 
             style="display: inline-block; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); 
                    color: white; padding: 12px 30px; text-decoration: none; border-radius: 6px; 
                    font-weight: bold; font-size: 16px;">
            Login to Your Account →
          </a>
        </div>
        
        <hr style="border: none; border-top: 1px solid #e0e0e0; margin: 20px 0;">
        
        <p style="font-size: 12px; color: #6c757d; text-align: center;">
          This is an automated message from Collectible Trading Post. Please do not reply to this email.<br>
          If you didn't request this account, please ignore this email or contact support.
        </p>
      </div>
    </div>
  `;

  const text = `
═══════════════════════════════════════
  WELCOME TO COLLECTIBLE TRADING POST
═══════════════════════════════════════

Hello ${data.username},

Your account has been successfully created!

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  YOUR LOGIN CREDENTIALS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Email:    ${data.email}
Username: ${data.username}
Password: ${data.password}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  ⚠️ IMPORTANT SECURITY NOTICE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This password was generated by the system. 
Please CHANGE YOUR PASSWORD IMMEDIATELY after your first login.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Login here: ${process.env.APP_URL || 'http://localhost:3000'}/login

Start exploring and trading collectibles now!

───────────────────────────────────────
This is an automated message. Please do not reply.
If you didn't request this account, please ignore this email.
───────────────────────────────────────
  `;

  try {
    // Check if SMTP credentials are configured
    if (!process.env.SMTP_USER || !process.env.SMTP_PASS) {
      console.warn('⚠️ SMTP credentials not configured. Email will not be sent.');
      console.log('📧 Email would be sent to:', data.email);
      console.log('📝 Generated Password:', data.password);
      console.log('📄 Email content:\n', text);
      return { success: false, error: 'SMTP credentials not configured' };
    }

    // Verify SMTP connection
    await transporter.verify();
    console.log('✅ SMTP connection verified');

    // Send email
    const info = await transporter.sendMail({
      from: process.env.EMAIL_FROM || `"Collectible Trading Post" <${process.env.SMTP_USER}>`,
      to: data.email,
      subject: '🎉 Welcome to Collectible Trading Post - Your Account Credentials',
      text,
      html,
    });

    console.log('✅ Welcome email sent successfully to:', data.email);
    console.log('📧 Message ID:', info.messageId);
    
    return { success: true, messageId: info.messageId };
  } catch (error) {
    console.error('❌ Failed to send welcome email:', error);
    console.log('📧 Credentials that would have been sent:');
    console.log(`   Email: ${data.email}`);
    console.log(`   Password: ${data.password}`);
    
    return { success: false, error };
  }
};